### ISSUE TITLE
Epic: Sport Field Information

### ISSUE THREAD

**Issue by katty-bird** [katty-bird/sports-fields#2]
User Story 1
As a user, I want to access details of each sport field, including a photo gallery, address, reviews, ratings, and a list of available equipment/facilities

**Comment by hientptran** [comment]
### Stand 28.06:
- Propagate overview tab with data from Firestore (name, address, opening hours, equipment, sanitary)
- Query sport field based on name
- Connected to my own firebase project

### To-Dos:
- [ ] Propagate ratings/reviews
- [ ] Connect to main firebase project
- [ ] Query based on geolocation
- [ ] Resolve linting issues
- [ ] Refactor

**Comment by hientptran** [comment]
### Stand 05.07
- Propagate information and reviews from Google Maps through Places API (Get Place Details with Place ID)
- Place ID is hard-coded

### To-Dos:
- [ ] Get information of clicked sport field
- [ ] Save data in Firebase
